coverage:
  status:
    patch: off
    project:
      default:
        paths:
        - "src/app"
        - "src/events"
        - "src/integrations"
        - "src/users"
        - "src/lists"
        threshold: 5.0
