[tool.ruff]
target-version = "py312"
extend-exclude = ["migrations"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN", "PT", "PD", "D100", "D104", "RUF012", "PLR0913"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.djlint]
custom_blocks = "element,slot,setvar"
preserve_blank_lines = true
ignore = "H006,H021"

[tool.coverage.run]
concurrency = ["greenlet"]
