name: Dry Run Cleanup Docker Images
on:
  workflow_dispatch:

jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: yamtrack
          dry-run: true
          keep-n-untagged: 15
          delete-ghost-images: true
          delete-orphaned-images: true
          validate: true
