name: Cleanup Docker Images
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: true
          keep-n-untagged: 15
          token: ${{ secrets.GITHUB_TOKEN }}